// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa32rklH7pcQk2qoUgwPfcoVfO2AqXGRg',
    appId: '1:242752869438:web:c8ac1bf4c5b8c754bc2d6f',
    messagingSenderId: '242752869438',
    projectId: 'todo-list-app-c1d1b',
    authDomain: 'todo-list-app-c1d1b.firebaseapp.com',
    storageBucket: 'todo-list-app-c1d1b.appspot.com',
    measurementId: 'G-2BBC7JW4N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4IJgBeaBrhVHgOglr1s0BlBqx8QXbQjA',
    appId: '1:242752869438:android:0e24f216e1eebb47bc2d6f',
    messagingSenderId: '242752869438',
    projectId: 'todo-list-app-c1d1b',
    storageBucket: 'todo-list-app-c1d1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsOS3ZJTrPWQ9Au86Hho01yhiIsVlgLPs',
    appId: '1:242752869438:ios:d42c22b140efae66bc2d6f',
    messagingSenderId: '242752869438',
    projectId: 'todo-list-app-c1d1b',
    storageBucket: 'todo-list-app-c1d1b.appspot.com',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsOS3ZJTrPWQ9Au86Hho01yhiIsVlgLPs',
    appId: '1:242752869438:ios:446423d581508c92bc2d6f',
    messagingSenderId: '242752869438',
    projectId: 'todo-list-app-c1d1b',
    storageBucket: 'todo-list-app-c1d1b.appspot.com',
    iosBundleId: 'com.example.todoListApp.RunnerTests',
  );
}
